// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzkCwv_nqKnm7VcDnAcML4XEaBpX6yDg',
    appId: '1:893334775463:web:28a880d0082dc908f89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    authDomain: 'civicsense-473112.firebaseapp.com',
    storageBucket: 'civicsense-473112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoKlxxs974kEFQGCDgctMXb4HBMHYE_c',
    appId: '1:893334775463:android:28a83117672767f7f89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    storageBucket: 'civicsense-473112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_yaaZ3LIZAcIkHDWS7Y4fmR_U5B8EZBs',
    appId: '1:893334775463:ios:0f7358414842212ff89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    storageBucket: 'civicsense-473112.firebasestorage.app',
    iosBundleId: 'com.example.civicTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzkCwv_nqKnm7VcDnAcML4XEaBpX6yDg',
    appId: '1:893334775463:web:d4fde9055c57e90ff89d82',
    messagingSenderId: '893334775463',
    projectId: 'civicsense-473112',
    authDomain: 'civicsense-473112.firebaseapp.com',
    storageBucket: 'civicsense-473112.firebasestorage.app',
  );
}
